wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
architecture:
  desc: null
  value: 3d-cnn
dataset:
  desc: null
  value: breathing_dataset
epochs:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.3
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1710903871.441049
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      - 103
      3:
      - 13
      - 16
      - 23
      4: 3.11.7
      5: 0.16.3
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
